spring:
  application:
    name: library_api
  datasource:
    url: 'jdbc:postgresql://172.31.0.3:5432/booksdb'
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.postgreSQLDialect